#!/usr/bin/env python3
"""Install the ICM Minimal Change Engineer into a project.

Usage:
    python3 install.py /path/to/your/project
    python3 install.py /path/to/your/project --dry-run
    python3 install.py /path/to/your/project --no-hooks

Everything lands in two places. `.claude/` gets the agent definition and the
hook wiring, because that is where Claude Code looks. Everything else goes in
`.icm/`, a single directory you can delete to uninstall.

Nothing is installed at your project root, and nothing existing is overwritten
without saying so. In particular this does not create a `tests/` or `hooks/`
directory in your project: the package keeps the gate under `tests/` for its
own use, and a project almost certainly has a `tests/` of its own already.

What you still do yourself, because no installer can guess it:

  * write a task file per task, declaring which paths that task may change
  * set ICM_TASK_FILE to it for the session, if you want the Stop hook to
    audit against it
  * restart Claude Code, or run /hooks, so the new settings are picked up

Exit codes:
    0  installed, or dry run completed
    1  refused: target is not a directory, or a needed source file is missing
    2  bad usage
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Governing paths worth protecting, checked against the target project so the
# generated config names directories that actually exist there rather than
# this package's own. Anything not found is written commented out, so the file
# doubles as a menu.
CANDIDATE_PROTECTED = [
    ("CONTEXT.md", "project context, read before work begins"),
    ("decisions/", "approved decision records"),
    ("docs/decisions/", "approved decision records"),
    ("adr/", "architecture decision records"),
    ("governance/", "governance definitions"),
    ("specs/", "canonical specifications"),
    ("approvals/", "human-owned approval artifacts"),
    ("tasks/", "task definitions; these declare the scope the gate enforces"),
]

HOOK_ENTRIES = {
    "PreToolUse": {
        "matcher": "Write|Edit|NotebookEdit",
        "hooks": [{"type": "command",
                   "command": "python3 .icm/hooks/protect_governing_files.py"}],
    },
    "Stop": {
        "hooks": [{"type": "command",
                   "command": "python3 .icm/hooks/run_scope_gate_on_stop.py"}],
    },
}

EXAMPLE_TASK = """# Example task file. Copy it per task; do not edit it during a task.
#
# allowed_paths is the authorization the gate enforces. The agent may not
# write or widen it -- if the task file changes during the work, the gate
# refuses to certify the run at all (exit 4). Commit this file and treat it
# as read-only for the agent.
#
# Run the gate:  python3 .icm/scope_gate.py --task tasks/this-file.yaml --repo .

task: Describe the one thing this task changes.
done_when: State the observable condition that means it is finished.

allowed_paths:
  - src/example.py

protected_paths:
  - approvals/
  - decisions/
  - tasks/

authorized_protected_paths: []
"""


class Installer:
    def __init__(self, target, dry_run, with_hooks):
        self.target = target
        self.dry_run = dry_run
        self.with_hooks = with_hooks
        self.done = []
        self.skipped = []

    def note(self, message):
        self.done.append(message)

    def skip(self, message):
        self.skipped.append(message)

    def copy(self, src, rel_dest, label):
        dest = self.target / rel_dest
        if not src.is_file():
            raise SystemExit("error - missing from this package: %s" % src)
        if dest.exists() and dest.read_bytes() == src.read_bytes():
            self.skip("%s already up to date" % rel_dest)
            return
        verb = "would write" if self.dry_run else "wrote"
        if not self.dry_run:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
        self.note("%s %s  (%s)" % (verb, rel_dest, label))

    def write(self, rel_dest, content, label, overwrite=False):
        dest = self.target / rel_dest
        if dest.exists() and not overwrite:
            self.skip("%s already exists, left alone" % rel_dest)
            return
        verb = "would write" if self.dry_run else "wrote"
        if not self.dry_run:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
        self.note("%s %s  (%s)" % (verb, rel_dest, label))

    def protected_paths_config(self):
        """Seed the protected list from what the target project actually has."""
        lines = [
            "# Paths the PreToolUse hook refuses to let the agent edit.",
            "# Generated by install.py from what this project contains.",
            "# Uncomment anything you add later. There is no in-session",
            "# override: a human edits this file, or the request is refused.",
            "",
        ]
        found = 0
        for path, why in CANDIDATE_PROTECTED:
            # tasks/ is never commented out. This installer creates it, so a
            # scan of the project before installing always finds it absent,
            # and leaving it unprotected is the exact hole F13 closed: task
            # files declare the scope the gate enforces, so an agent able to
            # edit one can widen its own permissions and pass its own audit.
            always_on = path == "tasks/"
            exists = always_on or (self.target / path.rstrip("/")).exists()
            if exists and not always_on:
                found += 1
            prefix = "" if exists else "# "
            lines.append("%s%-20s # %s" % (prefix, path, why))
        lines.append("")
        if not found:
            lines.append("# Nothing matched in this project. Uncomment what")
            lines.append("# applies, or the hook has nothing to protect.")
            lines.append("")
        return "\n".join(lines), found

    def merge_settings(self):
        """Add the hook entries to .claude/settings.json without clobbering."""
        path = self.target / ".claude" / "settings.json"
        try:
            settings = json.loads(path.read_text(encoding="utf-8"))
            existed = True
        except FileNotFoundError:
            settings, existed = {}, False
        except (OSError, json.JSONDecodeError) as error:
            self.skip(".claude/settings.json is not readable JSON (%s); "
                      "hook wiring left for you to add by hand" % error)
            return

        hooks = settings.setdefault("hooks", {})
        added = []
        for event, entry in HOOK_ENTRIES.items():
            existing = hooks.setdefault(event, [])
            commands = [h.get("command")
                        for item in existing for h in item.get("hooks", [])]
            if entry["hooks"][0]["command"] in commands:
                continue
            existing.append(entry)
            added.append(event)

        if not added:
            self.skip("hook wiring already present in .claude/settings.json")
            return
        verb = "would wire" if self.dry_run else "wired"
        if not self.dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(settings, indent=2) + "\n",
                            encoding="utf-8")
        self.note("%s %s into .claude/settings.json%s"
                  % (verb, " and ".join(added),
                     "" if existed else "  (created)"))

    def run(self):
        self.copy(HERE / "agent" / "icm-minimal-change-engineer.md",
                  Path(".claude") / "agents" / "icm-minimal-change-engineer.md",
                  "the agent definition")
        self.copy(HERE / "tests" / "scope_gate.py",
                  Path(".icm") / "scope_gate.py",
                  "the deterministic scope gate")

        found = 0
        if self.with_hooks:
            for name in ("protect_governing_files.py",
                         "run_scope_gate_on_stop.py"):
                self.copy(HERE / "hooks" / name,
                          Path(".icm") / "hooks" / name, "hook")
            config, found = self.protected_paths_config()
            self.write(Path(".icm") / "hooks" / "protected-paths.txt", config,
                       "%d governing path(s) found in this project" % found)
            self.merge_settings()

        self.write(Path("tasks") / "example-task.yaml", EXAMPLE_TASK,
                   "example task file")
        return found


def main():
    parser = argparse.ArgumentParser(
        description="Install the ICM Minimal Change Engineer into a project.")
    parser.add_argument("project", help="path to the project to install into")
    parser.add_argument("--dry-run", action="store_true",
                        help="show what would happen, change nothing")
    parser.add_argument("--no-hooks", action="store_true",
                        help="agent definition and gate only, no enforcement")
    args = parser.parse_args()

    target = Path(args.project).resolve()
    if not target.is_dir():
        print("error - %s is not a directory" % target, file=sys.stderr)
        return 1

    installer = Installer(target, args.dry_run, not args.no_hooks)
    found = installer.run()

    print("%s %s\n" % ("Would install into" if args.dry_run
                       else "Installed into", target))
    for line in installer.done:
        print("  %s" % line)
    for line in installer.skipped:
        print("  - %s" % line)

    if not (target / ".git").exists():
        print("\n  ! %s is not a git repository. The scope gate reads a git\n"
              "    diff, so it cannot audit anything here until you run\n"
              "    'git init' and make a first commit." % target.name)
    if installer.with_hooks and not found:
        print("\n  ! No governing files were found to protect. Edit\n"
              "    .icm/hooks/protected-paths.txt, or the PreToolUse hook\n"
              "    will allow every edit.")

    if args.dry_run:
        print("\nDry run. Nothing was changed.")
        return 0

    print("""
Next, and these are yours to do:

  1. Write a task file. Copy tasks/example-task.yaml and set allowed_paths
     to the files that task may change. Commit it.
  2. Restart Claude Code, or run /hooks, so it picks up the new settings.
     A settings file created mid-session is not noticed until then.
  3. Use the agent by name, pointing it at the task file.

To audit any change by hand, at any time:

  python3 .icm/scope_gate.py --task tasks/your-task.yaml --repo .

  exit 0 = in scope. 1 = touched something it should not have.
  2 = touched a protected file. 4 = rewrote its own permissions.

To uninstall: delete .icm/, remove the agent file from .claude/agents/, and
remove the two hook entries from .claude/settings.json.""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
